// lib/core/constants/pakistan_cities.dart

/// Curated list of major Pakistani cities, alphabetically sorted.
/// Used by [PakistanCityField] as the dropdown options.
/// The sentinel value 'Other...' must always be the last entry.
const List<String> kPakistanCities = [
  'Abbottabad',
  'Bahawalpur',
  'Chakwal',
  'Chiniot',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Faisalabad',
  'Gujranwala',
  'Gujrat',
  'Hafizabad',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jhelum',
  'Karachi',
  'Kasur',
  'Khanewal',
  'Khushab',
  'Lahore',
  'Larkana',
  'Layyah',
  'Lodhran',
  'Mansehra',
  'Mardan',
  'Mirpur Khas',
  'Multan',
  'Muzaffarabad',
  'Narowal',
  'Nawabshah',
  'Nowshera',
  'Okara',
  'Peshawar',
  'Quetta',
  'Rahim Yar Khan',
  'Rawalpindi',
  'Sadiqabad',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Sialkot',
  'Sukkur',
  'Swabi',
  'Swat',
  'Turbat',
  'Umerkot',
  'Vehari',
  'Wah Cantt',
  'Other...',
];
